// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by unplugin-vue-i18n-dts-generation (consts)
// Content-Hash: 4005fbdd

import _messagesI18n from '@intlify/unplugin-vue-i18n/messages'
import type {
  AllTranslationsGen,
  SupportedLanguagesGen,
  SupportedLanguageUnionGen,
  AllTranslationKeysGen
} from './i18n.types.d.ts'

export const supportedLanguages = ['en', 'en-US'] as const satisfies SupportedLanguagesGen
export const messages = {
  "en": {
    "App": {
      "fruits": {
        "apple": "Apple | Apples",
        "banana": "Banana | Bananas"
      },
      "fruitsLabel": "There are {amount} {fruit}",
      "greetings": "Hello Typescript friends!",
      "menu": ["home", "about"]
    }
  },
  "en-US": {
    "App": {
      "fruits": {"apple": "Apple | Apples", "banana": "Banana | Bananas"},
      "fruitsLabel": "There are {amount} {fruit}",
      "greetings": "Hello Typescript friends!",
      "menu": ["home", "about"]
    }
  }
} as const

// Type-safe i18n messages
export const messagesI18n = _messagesI18n as unknown as AllTranslationsGen

// Helper to get all translation keys
export const allTranslationKeys: AllTranslationKeysGen[] = [
  'App.fruits.apple',
  'App.fruits.banana',
  'App.fruitsLabel',
  'App.greetings',
  'App.menu',
  'App.menu.0',
  'App.menu.1'
]
