// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by unplugin-vue-i18n-dts-generation (deterministic)
// Content-Hash: c37772b6

import _messagesI18n from '@intlify/unplugin-vue-i18n/messages'

export const supportedLanguages = ['en', 'en-US'] as const
export const messages = {"en":{"App":{"fruits":{"apple":"Apple | Apples","banana":"Banana | Bananas"},"fruitsLabel":"There are {amount} {fruit}","greetings":"Hello Typescript friends!","menu":["home","about"]}},"en-US":{"App":{"fruits":{"apple":"Apple | Apples","banana":"Banana | Bananas"},"fruitsLabel":"There are {amount} {fruit}","greetings":"Hello Typescript friends!","menu":["home","about"]}}} as const
export type AllTranslationKeysGen = 'App.fruits.apple' | 'App.fruits.banana' | 'App.fruitsLabel' | 'App.greetings' | 'App.menu' | 'App.menu.0' | 'App.menu.1'
export type SupportedLanguagesGen = typeof supportedLanguages
export type SupportedLanguageUnionGen = typeof supportedLanguages[number]
export type AllLocaleGen = typeof  messages['en']
export type AllTranslationsGen = typeof messages // Record<SupportedLanguageUnionGen, AllLocaleGen>
export const messagesI18n = _messagesI18n as unknown as AllTranslationsGen
