// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by unplugin-vue-i18n-dts-generation (types)
// Content-Hash: c37772b6

import type { I18nOptions } from 'vue-i18n'

export type AllTranslationKeysGen = 'App.fruits.apple' | 'App.fruits.banana' | 'App.fruitsLabel' | 'App.greetings' | 'App.menu' | 'App.menu.0' | 'App.menu.1'
export type SupportedLanguagesGen = readonly ['en', 'en-US']
export type SupportedLanguageUnionGen = SupportedLanguagesGen[number]

// Message structure types
export type AllLocaleGen = {
  "App": {
    "fruits": {
      "apple": "Apple | Apples",
      "banana": "Banana | Bananas"
    },
    "fruitsLabel": "There are {amount} {fruit}",
    "greetings": "Hello Typescript friends!",
    "menu": [
      "home",
      "about"
    ]
  }
}
export type AllTranslationsGen = Record<SupportedLanguageUnionGen, AllLocaleGen>

// Type-safe translate function parameters
export type TranslateParams = (string | number | undefined | null) | Record<string, unknown>

// I18n config options (excludes messages as they're provided by the plugin)
export type I18nConfigOptions = Omit<I18nOptions<AllLocaleGen, {}, {}, SupportedLanguageUnionGen, false>, 'messages'>
