// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by unplugin-vue-i18n-dts-generation (deterministic)
// Content-Hash: 4f63b3bf
declare const _SupportedLanguages: readonly ['de', 'en']
const _messages = {"fruits":["apple","banana"],"greeting":"Hello","nested":{"menu":["home","about"],"title":"Welcome"}} as const
export type AllTranslationKeysGen = 'fruits' | 'greeting' | 'nested.menu' | 'nested.title'
export type SupportedLanguagesGen = typeof _SupportedLanguages
export type SupportedLanguageUnionGen = typeof _SupportedLanguages[number]
export type AllTranslationsGen = typeof _messages
