import { describe, it, expect } from 'vitest'
import { toDtsContent } from './generator'

describe('toDtsContent', () => {
  it('should generate basic type definitions', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {
        hello: 'Hello',
        world: 'World',
      },
      supportedLanguages: ['en', 'de'],
    })

    expect(result).toContain("export type AllTranslationKeysGen = 'hello' | 'world'")
    expect(result).toContain("declare const _SupportedLanguages: readonly ['en', 'de']")
    expect(result).toContain('export type SupportedLanguagesGen = typeof _SupportedLanguages')
    expect(result).toContain('export type SupportedLanguageUnionGen = typeof _SupportedLanguages[number]')
    expect(result).toContain('export type AllTranslationsGen = typeof _messages')
  })

  it('should handle nested message structure', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {
        nav: {
          home: 'Home',
          about: 'About',
        },
        forms: {
          submit: 'Submit',
        },
      },
      supportedLanguages: ['en'],
    })

    expect(result).toContain("'forms.submit'")
    expect(result).toContain("'nav.about'")
    expect(result).toContain("'nav.home'")
  })

  it('should use custom banner when provided', () => {
    const customBanner = '// Custom banner\n// Do not edit\n'
    const result = toDtsContent({
      messagesForBaseLocale: { test: 'test' },
      supportedLanguages: ['en'],
      banner: customBanner,
    })

    expect(result.startsWith(customBanner)).toBe(true)
    expect(result).not.toContain('AUTO-GENERATED FILE')
  })

  it('should use default banner when not provided', () => {
    const result = toDtsContent({
      messagesForBaseLocale: { test: 'test' },
      supportedLanguages: ['en'],
    })

    expect(result).toContain('AUTO-GENERATED FILE. DO NOT EDIT.')
    expect(result).toContain('Generated by unplugin-vue-i18n-dts-generation')
    expect(result).toContain('Content-Hash:')
  })

  it('should apply custom key transformation', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {
        userProfile: 'Profile',
        userSettings: 'Settings',
        adminDashboard: 'Dashboard',
      },
      supportedLanguages: ['en'],
      transformKeys: (keys) => keys.filter(k => !k.startsWith('admin')),
    })

    expect(result).toContain("'userProfile'")
    expect(result).toContain("'userSettings'")
    expect(result).not.toContain("'adminDashboard'")
  })

  it('should handle empty messages', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {},
      supportedLanguages: ['en'],
    })

    expect(result).toContain('export type AllTranslationKeysGen = never')
  })

  it('should sort languages alphabetically', () => {
    const result = toDtsContent({
      messagesForBaseLocale: { test: 'test' },
      supportedLanguages: ['zh', 'en', 'de', 'fr'],
    })

    // Languages should be in the same order as provided (already sorted in plugin)
    expect(result).toContain("declare const _SupportedLanguages: readonly ['zh', 'en', 'de', 'fr']")
  })

  it('should handle arrays in messages', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {
        items: ['item1', 'item2'],
        nested: {
          list: ['a', 'b'],
        },
      },
      supportedLanguages: ['en'],
    })

    expect(result).toContain("'items'")
    expect(result).toContain("'nested.list'")
  })

  it('should normalize line endings', () => {
    const result = toDtsContent({
      messagesForBaseLocale: { test: 'test' },
      supportedLanguages: ['en'],
    })

    expect(result).not.toContain('\r\n')
    expect(result).not.toContain('\r')
    expect(result).toMatch(/\n$/)
    expect(result).not.toMatch(/\n\n$/)
  })

  it('should generate deterministic output', () => {
    const params = {
      messagesForBaseLocale: {
        z: 'Z value',
        a: 'A value',
        m: {
          y: 'Y value',
          b: 'B value',
        },
      },
      supportedLanguages: ['en', 'de'],
    }

    const result1 = toDtsContent(params)
    const result2 = toDtsContent(params)

    expect(result1).toBe(result2)
  })

  it('should properly escape special characters in JSON', () => {
    const result = toDtsContent({
      messagesForBaseLocale: {
        quote: 'He said "Hello"',
        backslash: 'Path\\to\\file',
        newline: 'Line 1\nLine 2',
      },
      supportedLanguages: ['en'],
    })

    expect(result).toContain('"He said \\"Hello\\""')
    expect(result).toContain('"Path\\\\to\\\\file"')
  })
})